name: Release
on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    name: Publish packages to gh registry
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.10]
    steps:
      - name: Git Checkout
        uses: actions/checkout@master

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup npm
        run: npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

      - name: Install dependencies
        run: npm install

      - name: Bootstrap learna
        run: npx lerna bootstrap

      - name: Build packages
        run: npx lerna run build

      - name: Publish packages
        run: npx lerna publish

      - name: Build github release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false