name: Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Publish packages to gh registry
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.10]
    steps:
      - name: Git Checkout
        uses: actions/checkout@master

      - name: Build github release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false