name: Test
on:
  pull_request:

jobs:
  release:
    name: Run linter and tests
    container: node:16.14.2-alpine
    steps:
      - name: Git Checkout
        uses: actions/checkout@master

      - name: Setup npm
        run: npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

      - name: Install dependencies
        run: npm install
        
      - name: Bootstrap learna
        run: npx lerna bootstrap

      - name: Run tests
        run: npx lerna run test