name: Test
on:
  push:

jobs:
  release:
    name: Run linter and tests 
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    strategy:
      matrix:
        node-version: [16.10]
    steps:
      - name: Git Checkout
        uses: actions/checkout@master

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        
      - name: Bootstrap learna
        run: npx lerna bootstrap

      - name: Run tests
        run: npx lerna run test