name: Typedoc
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Generate TS docs and publish to ghp
    container: node:16.14.2-alpine
    steps:
      - name: Git Checkout
        uses: actions/checkout@master

      - name: Setup npm
        run: npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

      - name: Install dependencies
        run: npm install

      - name: Bootstrap learna
        run: npx lerna bootstrap

      - name: Generate docs
        run: npx typedoc

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/typedoc
          cname: sdk.tzkt.io
